"""alter user model

Revision ID: 804d9f0c6745
Revises: ebbd33b01f13
Create Date: 2021-05-28 20:08:26.758880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804d9f0c6745'
down_revision = 'ebbd33b01f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
