"""create user model

Revision ID: ebbd33b01f13
Revises: 
Create Date: 2021-05-28 19:42:34.091726

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from werkzeug.security import generate_password_hash

revision = 'ebbd33b01f13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    list_type_table = op.create_table('users',
                                      sa.Column('id', sa.Integer(), nullable=False),
                                      sa.Column('email', sa.String(length=120), nullable=True),
                                      sa.Column('password_hash', sa.String(length=128), nullable=True),
                                      sa.Column('name', sa.String(length=255), nullable=True),
                                      sa.PrimaryKeyConstraint('id')
                                      )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###

    op.bulk_insert(
        list_type_table,
        [
            {
                'email': 'admin@site.study',
                'password_hash': generate_password_hash('admin', method='sha256'),
                'name': 'Администратор'},
            {
                'email': 'denis@site.study',
                'password_hash': generate_password_hash('denis', method='sha256'),
                'name': 'Романов Денис Игоревич'},
            {
                'email': 'maxim@site.study',
                'password_hash': generate_password_hash('maxim', method='sha256'),
                'name': 'Матвеев Максим Филиппович'},
            {
                'email': 'kirill@site.study',
                'password_hash': generate_password_hash('kirill', method='sha256'),
                'name': 'Семенов Кирилл Андреевич'},
            {
                'email': 'marsel@site.study',
                'password_hash': generate_password_hash('marsel', method='sha256'),
                'name': 'Орлов Марсель Максимович'},
            {
                'email': 'kate@site.study',
                'password_hash': generate_password_hash('kate', method='sha256'),
                'name': 'Масленникова Екатерина Ивановна'},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
